all:
	javac group23/pacman/*.java
	javac group23/pacman/model/*.java
	javac group23/pacman/controller/*.java
	javac group23/pacman/view/*.java

run:
	javac group23/pacman/*.java
	javac group23/pacman/model/*.java
	javac group23/pacman/controller/*.java
	javac group23/pacman/view/*.java
	java group23.pacman.MainApp

clean:
	rm -rf group23/pacman/model/*.class
	rm -rf group23/pacman/controller/*.class
	rm -rf group23/pacman/view/*.class
	rm -rf *.class
